# Launch a ros master with the controller manager and associated services
version: "3.8"

services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile.noetic
    image: autobots-visman/pick-and-place:latest
    network_mode: host
    volumes:
      - ./:/catkin_ws/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    environment:
      DISPLAY: $DISPLAY
    # TODO: gazebo runs better with a GPU, but this would require inheriting
    # from the cuda image and installing ros
  gknet-gpu:
    build:
      context: vendor/GraspKpNet
      dockerfile: docker/Dockerfile.noetic
    image: ivalab/gknet:latest
    network_mode: host
    shm_size: 2gb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    environment:
      DISPLAY: $DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
